Feat - Add localization and Light/Dark mode use to demo
TuuZzee/fe-monorepo pull request #7
Opened 2023-03-28 10:09 UTC by alive2020

## Scope

- @namespace/website

## Description

Change Type:

```
- feat:       A new feature
```

Change logs:

- Add language change btn (en/ko)
- Add dark/light mode switch button

2023-03-29 01:59 UTC, TuuZzee commented on packages/storybook/package.json
> +    "storybook-dark-mode": "^2.1.1"
This needs to be moved into the `peerDependencies` above and added to the root package.json into it's `devDependencies`. This is to help keeping track of namespace packages (for upgrade and monitoring).

2023-03-29 02:01 UTC, TuuZzee commented on packages/websites/app-micro-fe/container/pages/index.js
> +      <TopNavBar
I think the useContext can be moved directly in the `TopNavBar` component so we don't have to set it up on all pages. Since this can be managed by the component directly.

2023-03-29 02:01 UTC, TuuZzee commented on packages/websites/app-micro-fe/container/pages/template.js
> +      <TopNavBar
Same here as [above](https://github.com/TuuZzee/fe-monorepo/pull/7/files#r1151317003)

2023-03-29 02:05 UTC, TuuZzee commented on packages/websites/app-micro-fe/container/src/components/shared/TopNavBar.js
> +const light = 'light';
Those const values are already available in their related context/util so we don't have to duplicate them: 
- dark/light can be imported from `packages/websites/shared/contexts/UiUxContext.js`
- en/ko can be imported from `packages/websites/shared/utils/intl-i18n.js`

2023-03-29 02:09 UTC, TuuZzee commented on packages/websites/app-micro-fe/container/src/styles/darkTheme.js
> +      body: `${colors.blackH303234} !important`,
Are those `!important` ? I think it would be better to have only color values here and no other CSS rule.

2023-03-29 02:12 UTC, TuuZzee commented on packages/websites/app-micro-fe/template/src/styles/darkTheme.js
> +      title: `${colors.whiteHFFFFFF} !important`,
I think it would be good to have each demo project to use different base color theme to emphasize that this is an addtional layer of customization. If all would use the same then we would move this to the @namespace/web-shared space.

2023-03-29 02:18 UTC, TuuZzee requested changes
I left some recommendations in comments to help enhance this already good PR :)

2023-04-07 07:26 UTC, alive2020 commented on packages/storybook/package.json
> +    "storybook-dark-mode": "^2.1.1"
I forgot to delete this, I've decided not to use it.

2023-04-07 07:29 UTC, alive2020 commented on packages/websites/app-micro-fe/container/pages/index.js
> +      <TopNavBar
we are using it at web-template and web-engineering-portal also, it should be separate for reuse, isn't it?

2023-04-07 08:20 UTC, alive2020 commented on packages/websites/app-micro-fe/container/src/components/shared/TopNavBar.js
> +const light = 'light';
imported ~

2023-04-07 08:20 UTC, alive2020 commented on packages/websites/app-micro-fe/container/src/components/shared/TopNavBar.js
> +  const handleThemeChange = () => {
Refactored.

2023-04-07 08:22 UTC, alive2020 commented on packages/websites/app-micro-fe/container/src/styles/darkTheme.js
> +      body: `${colors.blackH303234} !important`,
removed important, only for the body needs Important otherwise the color doesn't apply.

2023-04-07 08:25 UTC, alive2020 commented on packages/websites/app-micro-fe/template/src/styles/darkTheme.js
> +      title: `${colors.whiteHFFFFFF} !important`,
mmm.. for now i just deleted drom container and template and reusing themes from @namespace/web-app-micro-fe-shared, didn't touch  @namespace/web-shared

2023-04-10 03:04 UTC, TuuZzee commented on packages/websites/app-micro-fe/container/pages/index.js
> +      <TopNavBar
I have made a [commit ](https://github.com/TuuZzee/fe-monorepo/pull/7/commits/56615b8bc439d7defe3a94b0aad56616cc9163f3)that might explain better the idea. It's to avoid having to pass the props to `TopNavBar` component since it's handled directly there.

2023-04-10 08:45 UTC, TuuZzee approved these changes

2023-04-10 08:45 UTC, merged